name: Prettier

# This action works with pull requests and pushes on the main branch
on:
    pull_request:
    push:
        branches: [main]

jobs:
    prettier:
        name: Prettier
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 20
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x
            - name: Install dependencies
              run: npm install -D
            - name: Check formatting with Prettier
              run: npm run prettier:check
    linter:
        name: Linter
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 20
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x
            - name: Install dependencies
              run: npm install -D
            - name: Lint with eslint
              run: npm run lint
